services:
  mongo:
    image: mongo:8.0
    container_name: mongo-atlas-demo-local
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: schooldb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
