spring.application.name=mongo-atlas-springdata-java21-improved
server.port=8080

spring.data.mongodb.uri=${MONGODB_ATLAS_URI:mongodb://localhost:27017/schooldb}
spring.data.mongodb.auto-index-creation=true

spring.jackson.default-property-inclusion=non_null

logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

spring.profiles.active=atlas
